theme: jekyll-theme-hacker
title: 3mam
author: Konrad Chmielecki
avatar: "/assets/img/avatar-icon.png"
round-avatar: true
social-network-links:
    linkedin: konrad-chmielecki
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false
plugins:
  - jekyll-sitemap
