theme: jekyll-theme-hacker
title: 3mam
author: Konrad Chmielecki
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
plugins:
  - jekyll-sitemap
